name: wolfictl-lint
runs:
  using: composite

  steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        repository: wolfi-dev/wolfictl
        path: wolfictl-setup-gha

    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: '1.19'
        check-latest: true

    - id: build
      shell: bash
      run: |
        cd wolfictl-setup-gha
        make wolfictl
        mv wolfictl /home/runner/go/bin/
        cd ..
        rm -rf wolfictl-setup-gha
