name: wolfictl-lint
runs:
  using: composite
  steps:
    - uses: actions/checkout@main
      with:
        repository: wolfi-dev/wolfictl
        path: wolfictl-setup-gha
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - id: build
      shell: bash
      run: |
        cd wolfictl-setup-gha
        make wolfictl
        mv wolfictl /home/runner/go/bin/
        rm -rf wolfictl-setup-gha