name: wolfictl-lint
runs:
  using: composite

  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: wolfi-dev/wolfictl
        path: wolfictl-setup-gha

    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: '1.21'
        check-latest: true

    - id: build
      shell: bash
      run: |
        cd wolfictl-setup-gha
        make wolfictl
        mv wolfictl /home/runner/go/bin/
        cd ..
        rm -rf wolfictl-setup-gha
