name: ci

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.21'
          check-latest: true

      - uses: chainguard-dev/actions/goimports@main
      - run: make wolfictl
      - run: make test

  wolfictl-text:
    name: wolfictl text on wolfi-dev/os
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.21'
          check-latest: true

      - run: make wolfictl
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: 'wolfi-dev/os'
          path: 'wolfi-os'
      - run: |
          ./wolfictl text -d wolfi-os \
            --type=name \
            --pipeline-dir=wolfi-os/pipelines/ \
            --keyring-append=https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub \
            --repository-append=https://packages.wolfi.dev/bootstrap/stage3
