name: release

on:
  schedule:
    - cron: '0 0 * * 1' # weekly on Monday at 00:00
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Bump patch version and push tag
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
